### PR TITLE
Add Solaris 11 support

### PR DESCRIPTION
**Pull request by nalyanyam**
And also parameterize allow_weak_crypto option which seems necessary on some
Solaris 11 systems

### CODE REVIEW

**Comment by emahags** [comment]
In addition to the spec tests you already have, I would like to see one that ensures that allow_weak_crypto gets set if you configure it. I'll see if I can get the tests working again, looks like I haven't updated them since the travis changes.

**Comment by emahags** [comment]
I updated the metadata to work better with travis. I suggest you rebase your commit.

**Comment by emahags** [comment]
Thanks for your contribution!

**Comment by nalyanyam** [comment]
Thanks for merging. Was planning to add spec tests for allow_weak_crypto, but i can add this later and make a new PR.

**Comment by emahags** [comment]
@nalyanyam Ah, I see that I was a bit hasty, please do :)

**Pull request merged**
