### PR TITLE
Update spec tests.

### PR DESCRIPTION
**Pull request by nalyanyam**
Add spec tests for allow_weak_crypto option and more informative error
message for SunOS kernelrelease without defined package defaults

### CODE REVIEW

**Comment by nalyanyam** [comment]
@emahags 
Spec checks fails for the following versions:

PUPPET_GEM_VERSION = >4

PUPPET_GEM_VERSION = >4.3.0

I will try to check what changes are needed to allow compatibility for the above versions.

**Comment by nalyanyam** [comment]
@emahags 
Spec tests passed (Including failed Puppet Ver 4 tests) after updating a bunch of files, I hope i did not spoil anything.

**Comment by emahags** [comment]
@nalyanyam Your middle commit (d084bae60c04a52a99833cc8068cb01ec22e1c47) looks a bit funky. I have already made a few of those changes in 621c050dc77f71c285f523e3206eed7e823dbfb7. Do you think you could rebase your changes against the latest master? That would allow you to fix the spelling error in that commit message as well.

**Comment by nalyanyam** [comment]
@emahags 
Ok. I will close this PR and create a clean PR after rebasing to include your changes.

**Pull request closed without merging**
